### ISSUE TITLE
i2c does not return correct value

### ISSUE THREAD

**Issue by zhaochenyuangit** [tomtor/ulp-i2c#8]
Hello,

it has been a long time when you wrote the code, but I saw your reply to one issue just a few week ago. If you are still maintaining this repo, could you answer a question about the stack usage? Thank you.

I am now using esp-idf version v4.2. On [https://docs.espressif.com/projects/esp-idf/en/v3.3.5/api-guides/ulp_instruction_set.html#note-about-addressing](url) it is said that the ULP expect all address in 32 bit words. So if we return from a sub-routine, should the programm counter not be shifted by 2 words, namly 8 bytes? But in your stack.S file, the programm counter is shifted by 16.

A similar question about read data from stack. In your i2c-util.S, read_intro, the slave address and internal register address are found by shifting the stackEnd by 16 and 12, which I cannot understand becasue they corresponds to 4 words and 3 words, at that place should we find nothing but garbage.

Edit: the code works, I have a temperature sensor, and I let the ULP wake up the CPU when the temperature exceeds 26°C (place my finger on the sensor to heat it up). And the function works as intended. But I am still very curious about how the stack is implemented, I appreciated it very much if you can declare it.   
Following original post: 
I oberserved that my programm always skip the next line when return from subroutine, so the address shift seems to be incorrect. Maybe Espressif has changed the grammar of ULP? Do you still remember the syntax when you wrote the code?

Best 
Zhao

**Comment by tomtor** [comment]
Hi, I compiled the example code a few weeks ago with a recent git version:

commit 9d34a1cd42f6f63b3c699c3fe8ec7216dd56f36a (HEAD -> master, origin/master, origin/HEAD)
Merge: 85565b827 988c88a6b
Author: Ivan Grokhotkov <ivan@espressif.com>
Date:   Tue Apr 27 08:52:09 2021 +0000

    Merge branch 'bugfix/optimise_esp_timer_get_time' into 'master'
    
    systimer: optimise esp_timer_get_time
    
    See merge request espressif/esp-idf!13335


That binary worked and I see now that you edited your issue and it works OK for you too.

The `psr` macro indeed adds 16 to the assembly `.` location, but that is correct because we have to skip 3 32bit instructions:

```
move \sr,next2
st \rx,r3,0
sub r3,r3,1
```

Note that `push` is not a real instruction, it translates to TWO assembly instructions!

This also assumes that `pos=.` is pointing to the last seen assembly instruction, not to the `move` instruction.

`read_intro` is called from `read8` or `read16` without new parameters, so the return address to `read8/16` is the most recent stack entry at `r3+4` and the return address to the caller of `read8/16` is at `r3+8` so the two parameters originally passed to `read8/16` are now at `r3+12` and `r3+16`
